### ISSUE TITLE
Contract IDs freshness is not possible. 

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#10504]
In general the contract ID discriminator freshness based on input/output as described in the [contract ID specification](https://github.com/digital-asset/daml/blob/main/daml-lf/spec/contract-id.rst#discriminator-freshness), is not possible. 

The reason is that in projected transaction, there is actually no proper way to known what is input and what is output. 
From a abstract point of view, you cannot have capture-avoiding substitution for contract ID of local contract. 

To work around this problem:

* In fully distributed framework (Canton): 
  1. we will use suffix to distinguish local from global CID (local without suffix, global with suffix) 
  2. we will do the minimal change to ensures that the evaluation result is never changed by suffixing of local CID.

* In Central Committer framework (Sandbox, KV) 
    We will continue to use non-suffixed CIDs and rely on the fact the ledger ensure no two contracts can be created with the same ID. 

Implementation wise this translates into: 

- [x] Disable completely the contract ID freshness check (done during preprocessing and dynamically) #10620
- [x] Enforcing that LF Comparisons (both Ordering **and** Equality) fail at runtime if comparing local vs global CID. (enforcing point i above)  #10630
  * Ordering is already failing, but we need to expose the error (it is currently an internal error),
  * Equality must be changed to fail when comparing a local and global CID with same discriminator,
- [x] #10675
  * Checking during preprocessing, that all the CIDs in commands are suffixed #10642
  * Adding a flag in the Engine Config to (dis/en)able this check (Sandbox = off, KV = off, Canton = on) #10642
  * Conformance tests #10654
- [x] Fix the CID specification accordingly  #10703

This is a breaking change, however it should not impact any production system that do not have malicious participant.
