### ISSUE TITLE
dlik: Update roadmap (1d)

### ISSUE THREAD

**Issue by meiersi-da** [digital-asset/daml#136]
Goal: the roadmap in #121 is up to date with our current plans, and invites input
from third-parties.

Note that #440 contains the roadmap as part of the SDK docs:
- [x] ensure roadmap in #121 is contained in #440 
- [x] link from #121 to docs for complete roadmap
- [x] explain SQL indexing work track
- [x] explain benchmarking and performance tuning
- [x] explain conformance test tooling
- [x] explain tech debt cleanup

**Comment by meiersi-da** [comment]
Done in #440.
