### ISSUE TITLE
Allow template to implement interfaces that define the same choice name

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#13653]
Currently, we forbid that a template implements two interfaces that define a choice with the same name.
(e.g. interface A defines choice Ch, interface B defines a choice Ch, and template T implements A and B).
 we decided to drop this constraint.
 - It makes possible to implement two interfaces that use same choice name
 - It makes it consistent with method calls
 - This solves the problem of Archive: we will have as much Archive choices as Interfaces + templates

- [x] Add an optional interfaceId field to exercise Node to track where inherited choices where defined #13643
- [x] Adap Command to take into input  part of #13660
  - take the templateId as input for template choice
  - take the interfaceId as input for interface choice
  (to avoid breaking change, we do not rename the `templateId` from the Exercise command in the ledger API protobuf)
- [ ] fix Participant  
   - [x] add `interfaceId` field in Exercise event proto #13660
   - [ ] ~add a collum in Event table to track the Exercise `interfaceId` field.~ 
   - [ ] internalize (tuple, choice) 
- [x] fix Daml-Script #13660
- [ ] fix codegen 
- [x] #13923
- [x] #13973
- [x] Get ride of [`inheritedChoices`](https://github.com/digital-asset/daml/blob/96a6fe62e4bc497c568482bc54e54e1e6df1b7bd/daml-lf/archive/src/main/protobuf/com/daml/daml_lf_dev/daml_lf_1.proto#L1542) in `Implements`  
  - [x] in compiler & in runtime #14068,
  - [x] #14038
- [x] #14075
- [x] relax collisions check #13939
- [ ] ~consider making the ledger API Command, allow to use an arbitrary `templateId` or `interfaceId`and try to infer the choice in all the inherited choice, crash in case the choice is ambiguous.~ (will not do it)
- [ ] ~consider adding a field in Exercise command to perform a dynamic type checking of the contract ID.~ (on hold until further notice)
- [ ] ~consider adding a filed in CreateAndExercise and ExerciseByKey to enable calling interface choice.~ (on hold until further notice)
- [x] double check everything is properly tested.

**Comment by S11001001** [comment]
Will there be any restrictions on the signatures of choices? While two choices can have the exact same signature and be completely unambiguous in Daml and LF, perhaps we may want to still have some restrictions for the principle of serializability (i.e. "you can represent it in Java").

**Comment by remyhaemmerle-da** [comment]
> Will there be any restrictions on the signatures of choices?

The compiler will continue to produce different signatures for each choice, i.e. it would be possible to unambiguously infer the ID of the template/interface where a choice is defined from the type of its LF argument. 

We do not want the engine nor the participant implementation to use on this assumption, however I do not see objections for the codegens to rely on this assumption. (Daml script will use that).  

> you can represent it in Java

 I am not sure I fully understand your point.  

To be more concrete consider the following modules: 
```haskell
module M1 where 

  interface I1 where
      getParty : Party
      choice C : ()
          controller getOwner this
          do pure ()
```
```haskell
module M2 where 

  interface I2 where
    getParty : Party
    choice C : ()
        controller getOwner this
        do pure ()
``` 
```haskell
module M3 where 

  template T
    with
      party : Party
    where
      signatory party
      implements M.I1 where
        getParty = party
      implements M.I2 where
        getParty = party
      choice C : ()
      controller party
        do pure ()
``` 

In LF the argument type of the choice C from:
- `I1` will be `M1:C`
- `I2` will be `M2:C`
- `T` will be `M3:C`

Note you will not be able to use twice the same choice name in the same module. 


We plan to make the template `T` valid. Is that a problem to represent its choices in Java ?

**Comment by S11001001** [comment]
> The compiler will continue to produce different signatures for each choice, i.e. it would be possible to unambiguously infer the ID of the template/interface where a choice is defined from the type of its LF argument.

@remyhaemmerle-da Sorry, I wasn't clear, I meant _considering only the members of the choice record argument and the choices' return types_. That is, excluding the choice nominal type.

The example you provide shows one example, where these are exactly the same for all choices. That's useful, but I'm also concerned with:

* is something like this example, but where the choice return types are different, allowed?
* Are there any restrictions that look anything like functional dependencies here?

This list isn't exhaustive; I'm interested in any restrictions that might arise.

**Comment by S11001001** [comment]
⬆️ is largely driven by [the Java codegen update plan](https://github.com/digital-asset/daml/issues/13668#issuecomment-1106899636), though also possibly relevant for TypeScript.

**Comment by S11001001** [comment]
> consider adding a filed in CreateAndExercise and ExerciseByKey to enable calling interface choice.

Is it definitely planned to do this?

**Comment by remyhaemmerle-da** [comment]
> consider adding a filed in CreateAndExercise and ExerciseByKey to enable calling interface choice.

Is it definitely planned to do this?

For now this is on hold. We will first implement retroactive instance and interface subscription.
