### ISSUE TITLE
Investigate app-runtime changes to allow templates to implement interfaces with clashing-name choices

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#13668]
Referring to #13653, lifting this requirement will likely have a knock-on effect on runtime components where we have interface support already. The outcome of this ticket should be:
- an analysis of how lifting the requirement will impact each affected runtime component
- a suggestion of how to change each affected runtime component to deal with the lifted requirement
- a clear statement of whether we expect some breaking change with regards to stable features (breaking changes with regards to interface support is expected, of course)

Possibly affected runtime components:
- [x] [Java codegen](#issuecomment-1106899636)
- [x] [LF interface library](#issuecomment-1106915404)
- [x] [TS codegen](#issuecomment-1110146425)
- [x] [HTTP JSON API Service](#issuecomment-1110218501)
- [x] [Scala codegen](#issuecomment-1126524659)

Unlikely to be affected but included for completeness:
- [x] [Trigger Service](#issuecomment-1110230864)

**Comment by S11001001** [comment]
## Java codegen

### Impact

Without changes, each overloaded choice name will get codegenned support for one of the choices, with the remainder silently discarded.

Java codegen takes the LF interface library as input; as the main structural invariant is lifted from the interface library, i.e. each template maps each `ChoiceName` to exactly one choice signature, its template and interface generators will stop compiling and need fixes.

### Suggested changes

In the current release, when generating code, _every_ choice method has a corresponding _flattened exercise method_, which allows specifying the choice arguments directly instead of constructing the choice record. For example, for this Daml code

```haskell
        choice TestTemplate_Unit : ()
          controller owner
          do return ()
        choice TestTemplate_Int : ()
          with x : Int
          controller owner
          do return ()
```

you get

```java
    public ExerciseCommand exerciseTestTemplate_Unit(TestTemplate_Unit arg) {/* elided implementation */}

    public ExerciseCommand exerciseTestTemplate_Unit() {
      return exerciseTestTemplate_Unit(new TestTemplate_Unit());
    }

    public ExerciseCommand exerciseTestTemplate_Int(TestTemplate_Int arg) {/* elided implementation */}

    public ExerciseCommand exerciseTestTemplate_Int(Long x) {
      return exerciseTestTemplate_Int(new TestTemplate_Int(x));
    }
```

and likewise for `createAndExercise` methods.

Suppose _fcrmt(c)_ is the sequence of Java types mapped from the members' types of the choice record type _c_. When generating _flattened exercise methods_ for choices [c₁..cₙ], if there exist two choices cⱼ, cₖ such that _j_ ≠ _k_ but _fcrmt(cⱼ)_ = _fcrmt(cₖ)_, _do not_ generate flattened exercise methods for any of [c₁..cₙ].

Instead, where the Java code to exercise might have been `cid.exerciseC(a, b)`, the Java programmer may invoke `cid.toIfc().exerciseC(a, b)`, where _Ifc_ is an interface type containing the desired choice _C_. This will convert the template contract ID to an interface contract ID, where the ambiguity may no longer apply.

This has the benefit of being completely backward-compatible, at the expense of the odd case where introducing a new choice in Daml may actually _remove_ generated methods from the Java code generated from that Daml, which the Java programmer may have been using.

### Will break

This will not break anything for existing Java codegen users on existing Daml code.

**Comment by S11001001** [comment]
## LF Interface library

### Impact

The interface library, in contrast with the LF decoded AST, encodes invariants about the serializable signatures in an LF archive as tightly as possible, so the codegens and JSON API have sound basis inputs. The `InterfaceReader` needs to loosen these restrictions, especially where the "one choice per name" might be implicitly assumed, and the data structures and functions dealing with choices will all need to change to account for more-than-one.

### Suggested changes

In retrospect, managing `DefTemplate` state dynamically purely by emptiness of the `unresolvedInheritedChoices` is more brittle than I desired. Instead, it (but not `DefInterface`) should contain a member ADT with two cases:

```scala
// 1
    choices: Map[Ref.ChoiceName, TemplateChoice[Ty]],
    unresolvedInheritedChoices: NonEmpty[Map[Ref.ChoiceName, Ref.TypeConName]],
// 2
    choices: Map[Ref.ChoiceName, NonEmpty[ImmArraySeq[TemplateChoice[Ty]]]],
```

Surprisingly, _it is not necessary to change the map key from `ChoiceName`_. The parameter type in the `TemplateChoice` is sufficient to identify the nominal choice.

### Will break

Any code that uses template signatures from the interface library. But this is what we want.

**Comment by S11001001** [comment]
## JSON API

### Impact

JSON API assumes that you can pass a template ID for a gRPC exercise of an interface choice; this will no longer be allowed by gRPC, but we should keep supporting it for JSON API's own argument interface.

There will be new error cases for when a choice resolution is ambiguous, similar to when package ID inference fails.

### Suggested changes

A choice resolution additionally produces an optional interface ID; this is reflected in the interface library. When an interface ID is yielded, JSON API must exercise _by interface ID_; otherwise, it must exercise by template ID.

For its own exercise endpoint, an optional `interfaceChoiceId` may be specified, whose default is the `templateId`.  (An interface ID will continue to be allowed as a `templateId` argument, subject to the restrictions below.)  The semantics depend on where the choices come from and what type of ID `interfaceChoiceId` is.

1. If a template ID is specified, and the template directly defines the choice, that is the selected choice; inherited choices are ignored.
2. If an interface ID is specified, the choice must come from the interface. This exactly matches current behavior.
3. If a template ID is specified, and the template _does not_ define the choice, but inherits choices with that name, what happens depends on how many:
    a. If only one, that choice is selected.
    b. If more than one, HTTP 400 indicating the interface IDs on which the choice is defined.

Note that it will continue to be required that `templateId` is not an interface ID in the exercise-by-key case; to exercise an ambiguous choice on an interface by key, users will specify the key's template type as `templateId` and the choice's interface as `interfaceChoiceId`.

create-and-exercise is an open question in #13653 at time of writing, so I have left that part TODO.

### Will break

This will not break anything for existing JSON API users on existing Daml code.

**Comment by S11001001** [comment]
## Trigger service

### Impact

The trigger runner's `Converter` may have to parse different commands; this doesn't imply any ambiguity for that conversion, though, as the exact defining interface-or-template is always statically known when compiling a trigger.

None of this complexity propagates upward to the trigger service.

### Suggested changes

Incorporate the new trigger runner.

### Will break

Triggers that were written against the older trigger library may break and need to be recompiled; the new triggers will require the newly-compiled trigger service as well.  There are no trigger-service-specific breaks.

**Comment by stefanobaghino-da** [comment]
We don't have to commit to a solution right away, I'll make sure to think more about this next week. For the time being let's re-prioritize Scala codegen work. In that area we have more freedom to make changes, as long as they don't break existing code. 🕷️

**Comment by S11001001** [comment]
## Scala codegen

### Impact

Codegen won't break in a way that is immediately apparent, but will have no way to generate the correct exercise method when confronted with overloaded names.  It will also currently fail if an interface-contract-ID appears in any signature, even though interface-contract-ID types are serializable.

Naturally, it must also adapt to changes in the LF interface library described above.

### Suggested changes

For every interface `If`, codegen an uninhabited marker type

```scala
sealed abstract class If extends Interface[If]
object If extends InterfaceCompanion[If] {
  override val id = // ...
  implicit final class `If syntax`[+` ExOn`](private val id : ` ExOn`) extends AnyVal {
    // exercise methods exactly like with templates
  }
}
```

Common utilities can be factored between the existing `TemplateCompanion` and the new `InterfaceCompanion`.  Note that `If` is uninhabited, so several members of `TemplateCompanion` will not make sense.

` exercise` will need a new argument, the optional interface ID.  Generated template exercise methods will not include this, and generated interface exercise methods will include it unconditionally.

Add to `object Template` a class `Implements[T, If]`.  This shouldn't have any usage but as a marker, but there's no problem adding data to this class if it turns out to be useful.

Add an implicit class to `object Template` for `ContractId[T]` that adds this method:

```scala
def toInterface[If](implicit ev: Implements[T, If]): ContractId[If]
```

and likewise an `unsafeToTemplate` to `object Interface` to provide the opposite conversion.  This will completely avoid the same-named-template problem with these methods, because the way you select the "right" interface is to simply use Scala's own name management.

`Template.CreateForExercise` and `Template.Key` also get `toInterface` with the same signature.  `unsafeToTemplate` is possible, but I cannot imagine a use case; these are strictly transient types.

In each generated template companion, add one `implicit val` for each interface `If` of type `Template.Implements[T, If]`.  The name should contain a space, and can contain the fully-qualified interface name to avoid collisions; there is no need to ever import it or refer to it explicitly.

```scala
// exercise
cid.toInterface[If].exerciseFoo(party, args...)
// exercise by key
Tpl.key((alice, 42)).toInterface[If].exerciseFoo(party, args...)
// create-and-exercise
Tpl(alice, 1, 2).createAnd.toInterface[If].exerciseFoo(party, args...)

// coerce interface-cid to template-cid
icid.unsafeToTemplate[Tpl].exerciseBar(party, args)
```

I am fairly certain we can elide the `toInterface` calls by means of implicits.  However, this should be an optional feature, if provided at all; it could be activated by means of an import.

### Will break

This will undo the inheritance added as a workaround in #13858; all existing calls to interface exercise methods will no longer compile.  As this feature has no external users, and possibly no internal users at time of writing, this is a minimal impact.

**Comment by stefanobaghino-da** [comment]
There has been progress with regards to the Java codegen. I'll report here the outcome of the conversation I had with @S11001001.

The idea is the following
* for every interface there will be a static singleton representing that interface
* for every interface implemented by a template, there will be a `toInterface` method defined on the template contract ID taking as an input a specific singleton and returning the interface contract ID expected by that conversion

This boils down to the following (the names are there only to illustrate the concept and are not to be considered final):

```java
templateContractId.toInterface(com.daml.Asset.INTERFACE).exerciseSomeChoice(arguments);
templateContractId.toInterface(com.example.Asset.INTERFACE).exerciseSomeChoice(arguments);
```

This will work for edge cases as the one above in which there is a clash in unqualified names, choice names and arguments at the same time.

Note that if you already have an interface contract ID you can invoke the choice method directly, making the experience uniform and especially well suited to focus your work around interfaces as we make them more prominent through Daml.

As part of the conversation, we also mentioned the following to allow to issue a create-and-exercise like so:

```java
templateContractId.create(arguments).toInterface(com.daml.Asset.INTERFACE).exerciseSomeChoice(arguments);
```

This looks sleek but after a second pass it doesn't seem feasible, since the object returned by `create` is a `CreateCommand` in our API. Since this is case, I'm wondering whether it would be better do rather add the following:

```java
templateContractId.createAndExerciseByInterface(com.daml.Asset.INTERFACE, createArgument, exerciseArgument);
templateContractId.createAndExerciseByInterface(com.example.Asset.INTERFACE, createArgument, exerciseArgument);
```

Which is not as sleek but probably easier and more in line with our current `createAndExercise` method we have generated code expose.

Regardless, the approach is a breaking change with regards to the current status of Java codegen for interfaces, which is fine since we're still in the early access stage and breaking changes are allowed before we move on to GA.

**Comment by S11001001** [comment]
> ```java
> templateContractId.createAnd(arguments)
> ```

with the minor caveat

```java
payload.createAnd()
```

**Comment by S11001001** [comment]
@stefanobaghino-da I've rewritten [Java codegen](https://github.com/digital-asset/daml/issues/13668#issuecomment-1106899636) to explain how to implement the new design.

**Comment by S11001001** [comment]
All of these have been completed. Some important followups:

* #14132
* #14056 
* #13993
* #14549
