### ISSUE TITLE
replace .toIfc() and .unsafeFromIfc(...) with singletons and overloads

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#13919]
Design from https://github.com/digital-asset/daml/issues/13668#issuecomment-1106899636 . For this part:

* [x] define `codegen.InterfaceCompanion`
* [x] generate named `INTERFACE` final subclass of `InterfaceCompanion` as static inner class of each interface, package-private ctor, singleton instance also named `INTERFACE`
* [x] replace `.toIfc()` with `.toInterface(pkg.Ifc.INTERFACE marker)`
* [x] rename `.unsafeFromIfc(...)` to `.unsafeFromInterface(...)`

**Comment by stefanobaghino-da** [comment]
Since we are renaming and we can still break: prepending `unsafe` to a method that could throw is not a common pattern in Java. I propose to:
* create an `UnimplementedInterfaceException` which can be used to report information about the error
* turn `unsafeFromIfc(...)` into `fromInterface(...) throws UnimplementedInterfaceException`

**Comment by S11001001** [comment]
@stefanobaghino-da `unsafeFromInterface` does not exist in cases where a template doesn't implement an interface, so there is never cause to throw such an exception. This is "unsafe" because we are coercing from interface-contract-ID to template-contract-ID, which we cannot check locally.

**Comment by stefanobaghino-da** [comment]
> @stefanobaghino-da `unsafeFromInterface` does not exist in cases where a template doesn't implement an interface, so there is never cause to throw such an exception. This is "unsafe" because we are coercing from interface-contract-ID to template-contract-ID, which we cannot check locally.

Does that throw an exception? Under what circumstances?

**Comment by S11001001** [comment]
> Does that throw an exception? Under what circumstances?

No, it doesn't.

```java
Foo.ContractId z = // ...
var bcid = Bar.ContractId.unsafeFromInterface(
    z.toInterface(some.SharedIface.INTERFACE));
bcid.exerciseSomeBarChoice(...); // submitting this exercise will fail
```

**Comment by stefanobaghino-da** [comment]
I see, thanks!
