### ISSUE TITLE
support interface inheritance of same-named choices in LF interface library

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#13918]
Follow the design in https://github.com/digital-asset/daml/issues/13668#issuecomment-1106915404

* [x] resolution sum with unified
    * [x] `directChoices` with same signature as unresolved `choices`, excludes inherited
    * [x] `resolvedChoices` with same signature as resolved `choices`, includes all
* fix clients
    * [x] Java codegen, attach any TODOs to #13921
    * [x] json-api, attach any TODOs to #13923
    * [x] Scala codegen, any TODOs to #13349
