### ISSUE TITLE
toInterface and unsafeToTemplate extension methods

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#13925]
Design https://github.com/digital-asset/daml/issues/13668#issuecomment-1126524659

* contract IDs
    * [x] `toInterface` in `object Template`
    * [x] `unsafeToTemplate` in `object Interface` (see #13924)
* [x] `Template.Key`, `toInterface` only
* [x] `Template.CreateForExercise`, `toInterface` only
* [x]  introduce `Template.Implements`
* [x] codegen `Template.Implements` instances, depends on #13924
