### ISSUE TITLE
generate uninhabited types for interfaces, with their choices, and resolve their contract IDs

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#13924]
Design https://github.com/digital-asset/daml/issues/13668#issuecomment-1126524659

* [x] handwritten `Interface` and `InterfaceCompanion` parents
    * [x] `cannotExist` method on `Interface` to emphasize the point
    * [x] factored with `TemplateCompanion`/`ValueRefCompanion` somehow
* [x] generate subclass of `Interface` for each interface
* [x] resolve `ContractId I` properly where `I` is an interface
