### ISSUE TITLE
remove inherited exercise methods

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#13921]
Design from https://github.com/digital-asset/daml/issues/13668#issuecomment-1106899636 .

Depends on:

* [x] #13918
* [x] #13919
* [x] #13920

For this part:

* [x] emit only directly-defined choices on templates in the `Exercises` interface
* [x] un-`ignore` [this test](https://github.com/digital-asset/daml/blob/a6dac18fb998cb3267abc3bcb23f55dd9a8e7cc5/language-support/java/codegen/src/ledger-tests/scala/com/digitalasset/InterfacesTest.scala#L23-L24) and fix it
* [x] mention that inherited exercise methods are removed in changelog; how to use `toInterface` or `createAnd().toInterface` instead
