### ISSUE TITLE
support interface inheritance of same-named choices in json-api

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#13923]
Design in https://github.com/digital-asset/daml/issues/13668#issuecomment-1110218501

* [x] extend `domain.ExerciseCommand` and `domain.CreateAndExerciseCommand` with optional `choiceInterfaceId`
* [x] change `PackageService.ResolveChoiceArgType`: accepts the optional choice interface ID, returns `Error \/ (TemplateId.RequiredPkg, iface.Type)`
* [x] use the new extra returned data to infer `choiceInterfaceId`
* [x] in `CommandService` `#exerciseCommand` and `#createAndExerciseCommand`, use `choiceInterfaceId` to fill in the new ledger API fields
* [x] un-`ignore` [this test](https://github.com/digital-asset/daml/blob/a6dac18fb998cb3267abc3bcb23f55dd9a8e7cc5/ledger-service/http-json/src/it/scala/http/HttpServiceIntegrationTest.scala#L76-L77) and fix it

Depends on

* [x] #13918
