### ISSUE TITLE
unified by-contract-ID/createAnd exercise interface, deprecate createAndExercise methods

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#13920]
Design from https://github.com/digital-asset/daml/issues/13668#issuecomment-1106899636 . For this part:

* [x] declare `codegen.Exercises<Cmd>` with `makeExerciseCmd`
* [x] implement `makeExerciseCmd` in `codegen.ContractId` which now implements `Exercises<ExerciseCommand>`
* [x] define `codegen.CreateAnd<...> implements Exercises<CreateAndExerciseCommand>`
* [x] define `createAnd()` on templates
* [x] move exercise methods from `ContractId` to separate generated interface with default methods in terms of `makeExerciseCmd`
* [x] define `codegen.ByKey<...> implements Exercises<ExerciseByKeyCommand>`
* [x] define `static byKey(...)` in terms of `ByKey` and `Exercises`
* [x] propagate extra `TemplateId` in the toInterface cases for create-and, by-key
* [x] emit deprecation annotation and maybe Javadoc for all existing `createAndExercise` and by-key methods
