### ISSUE TITLE
Investigate improvements to support interface subscriptions

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#14067]
Interface subscription are currently being designed in [this document](https://docs.google.com/document/d/1xpQI5AbEJdbpOWsjAUzOOTnJvTHTE4nDO1MnU7Ozng4/edit).

They are an important piece of enabling upgradable applications using interfaces. As such, having them as part of the first stable release is important. We should understand how those could be implemented on top of our components, in particular:
- [x] [HTTP JSON API Service](#issuecomment-1149150541)
- [x] [JavaScript bindings](#issuecomment-1171783723)
- [x] [Java bindings](#issuecomment-1164998509)

Engage with the design document and report the changes that are deemed necessary to make our components support interface subscriptions.

**Comment by S11001001** [comment]
## LF Interface library

It's not clear whether subscriptions will make it possible to universally treat an interface type as an alias or "pun" for its associated view type. For the purposes of these designs, I'm assuming that it will _not_. So interfaces will remain separate from the serializable type decls.

An ast interface will include a reference to the identifier of the associated view type, a serializable type. We copy that to `DefInterface` in the `InterfaceReader`.

Assuming that LF will require that view types are records with no type parameters, we include utilities

```scala
// EnvironmentInterface
def resolveInterfaceViewType(n: Ref.TypeConName): Option[Record.FWT]
// Interface
def resolveInterfaceViewType(n: Ref.QualifiedName): Option[Record.FWT]

// Interface companion
def interfaceViewResolver(findInterface: PartialFunction[PackageId, Interface])
    : PartialFunction[Ref.TypeConName, Record.FWT]
```

### Will break

Anything downstream that depends on the structure of `DefInterface`.

**Comment by S11001001** [comment]
## JSON API

Introduce 3 subtypes for `TemplateId.RequiredPkg`s that have been resolved by lookup with the internal `PackageService` as a template ID, interface ID, or "either". This is because we currently assume that a fully-qualified template ID can simply be turned into a template filter for the ledger API. The interface subscriptions feature invalidates that assumption, and probably some significantly more insidious cases (as that is just the one I spotted last I was examining the query code), so it seems worth doing away with the assumption statically.

For the purposes of the DB cache, we will consider interface IDs exactly like template IDs, and their payload types to be exactly their interface view types. So the contracts table will continue to be partitioned by template ID: updates for a template ID won't affect an interface ID's partition, _even if the same contract ID is present in both_.

On the contract table, remove the `contract_k primary key` constraint on `contract_id`, replacing it with a `primary key` constraint on `(contract_id, tpid)`. We must advance the `schemaVersion` as a result.

In `Queries#deleteContracts`, include the template IDs as arguments (I think we only need one, but adjust as needed), and when selecting rows for deletion. It sounds appealing to delete every view associated with a contract ID at once, but this entails race conditions more easily dealt with by not doing this.

When assembling a transaction or ACS request, we always set `include_create_arguments_blob = false`, `include_interface_view = true`.

When building `InsertDeleteStep`s for the database, we essentially want one create event per matching contract/interface, and likewise for archives. _TODO why streams won't let us conflate payloads_

### Will break

_TODO_

**Comment by S11001001** [comment]
## Java bindings
 
 (Largely with respect to #14033 as of this writing.)
 
 In `com.daml.ledger.javaapi.data`, extend the following classes to reflect changes to their protobuf counterparts:
 
 * add `Filter.Interface`, the pair of bools from proto `InterfaceFilter`
 * `InclusiveFilter`: add a `interfaceIds: @NotNull Map<@NotNull Identifier, @NotNull Filter.Interface>`. Add a static method `ofTemplateIds` to replace the current single-arg constructor, now deprecated.
 * `CreatedEvent`: add `interfaceViews: @NotNull Map<@NotNull Identifier, @NotNull DamlRecord>` and `failedInterfaceViews: @NotNull Map<@NotNull Identifier, @NotNull Status>`. NB: `Status` might not be the best choice; if we can narrow it down, we should.
 
 Existing constructors should default these to empty maps, _and be deprecated_ with a porting note, a version note, and fresh GitHub issue reference similar to #14039.
 
 Include proto to/from conversion changes; beware, this is not fully type-checked.
 
 ### Will break
 
 Users of transaction streams will likely encounter the deprecation warning on `new InclusiveFilter`, whose Javadoc directs them to `InclusiveFilter.ofTemplateIds`. If we don't do this, because we don't have a type-level distinction between template IDs and interface IDs, users are apt to try adding interface `Identifier`s to this existing set, which will not work.

**Comment by cocreature** [comment]
Two comments/suggestions on the JSON API changes:

1. Your query changes are slightly ill-defined: You can check that at the beginning of the query but a package upload for a running query can break this for a running query. In the participant, we were very explicit that it’s a requirement to never serve stale data meaning a package upload needs to take effect immediately. If I understand your proposal correctly, you check the restriction once at the beginning leaving you with the question of what you do if that invariant gets violated, e.g., you then get a create event that implements two interfaces. You could abort the stream or something like that. Alternatively, you could also enforce a much stricter rule: If there is an interface in CTIDS, then CTIDS must be a singleton set containing only that interface. I think for the typescript bindings (without multiplexing which is I believe still disabled), that would be sufficient and it’s easy to understand and resilient against later package uploads.
2. I recommend to not exploit the restrictions you impose on the queries in the output format and instead have an output format that is sufficiently general that you can support other queries later without changing the format just for those. That leads to a more complex output format right now but it’s much easier to extend it without breaking backwards compatibility or ending up with weird inconsistencies. One option would be to follow what the gRPC does and introduce an object with the keys being interface ids and the values being the the interface value.

**Comment by cocreature** [comment]
Java bindings changes look very reasonable.

**Comment by S11001001** [comment]
> Alternatively, you could also enforce a much stricter rule: If there is an interface in CTIDS, then CTIDS must be a singleton set containing only that interface.

@cocreature Thanks for pointing out the invalidation case. I will use this rule instead.

> 2\. I recommend to not exploit the restrictions you impose on the queries in the output format and instead have an output format that is sufficiently general that you can support other queries later without changing the format just for those.

The simple format is one of the goals of applying these restrictions. "The payload type of an interface ID is its interface view" is a simple metaphor to extend existing query uses. The more general format, such as any gRPC-inspired one, penalizes the simple single-query use case to support full multiquery generality.

To this point, the multiquery cases have imposed no additional complexity on single-query cases; it has always been possible to treat them as "one or list-of-n" functions as common in Python _et al_. The only artifact is `matchedQueries`, which can simply be ignored by single-query users. With this new feature, something's gotta give, and I do not think it should be the simple, more intuitive interface enabled by the single-query restrictions. Instead, the complex, multi-query use case should yield.

From discussions elsewhere arose the suggestion from @garyverhaegen-da that we can implemented the restricted form with the very nice-to-use "payload of interface ID is interface view" extension, and leave a more general multiquery result type to _a new endpoint_ in a later release. This is the plan I currently have in mind.

**Comment by S11001001** [comment]
## JavaScript bindings

(This somewhat depends on #14134.  Consider some form of interface contract ID from that proposal to be a prerequisite of this design.)

An interface contract ID type for interface `I` will be `ContractId<I>`, such that

```ts
type I = Interface<"pkgid:mod:I"> & IV
```

where `IV` is the interface view type.  Depending on the chosen semantics for the final LF implementation, this can probably be a reference, and the interface view should be included in the module dependencies of an interface.

Generate a `Serializer<I>` and declare it in TypeScript; its name should match what is generated for interface types as the `JsSerializerConRef` by `genTypeCon` in TsCodeGenMain.hs.  The serializer should be trivially derivable from `IV`'s serializer.

### Will break

This design breaks nothing itself, but #14134 or a similar required design breaks some current interface choice invocation expressions.  Neither that nor this design breaks any pre-interface features.
