### ISSUE TITLE
resolve retroactive interfaces in lf/interface library

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#14081]
* [x] prerequisite: retro implements available in `Ast.DefInterface`
* [x] #14820

Extend `EnvironmentInterface`, ~Interface~ `PackageSignature`, and `DefInterface` with `resolveRetroImplements`. These will resolve the various levels of the data structures.

* [x] `DefInterface#resolveRetroImplements`

As the pass-down resolver is `PartialFunction[Ref.Identifier, DefInterface[Ty]]` and derivatives thereof for `resolveChoices`, so `DefInterface` will have

```scala
type Setter[S, A] = (S, A => A) => S
def resolveRetroImplements[S](
  s: S,
  setTemplate: PartialFunction[Ref.Identifier, Setter[S, DefTemplate[Ty]]])
    : (S, DefInterface[Ty])
```

where `setTemplate` is the resolver. This will let us put the work of resolution in the interface library while adapting to existing postprocessed interface structures such as the json-api cache.

The implementation is a fold with `s` over the retro template references, looking up each with `setTemplate` in turn and filling in the new interface data if a `DefTemplate` is found, doing nothing if not. (This makes resolution distributive, which is useful for avoiding pointless errors while incrementally loading.) The resulting interface has the retros that were found removed from the `DefInterface`.

* [x] `Interface.resolveRetroImplements`
    * [x] test: #14820
* [x] `EnvironmentInterface#resolveRetroImplements`
    * [x] test: #14820

`Interface` has a similar resolution method, and `EnvironmentInterface` has one that takes no arguments and just updates itself.

* [x] json-api: `PackageService#State#append` needs an incremental application of `Interface.resolveRetroImplements`
    * [x] #14821
* [x] Java codegen: `CodeGenRunner.configureCodeGenScope` should apply resolution to `signatures`
    * [x] #14822
* [x] Scala codegen: simply apply `resolveRetroImplements` to `interfaces.suml1` in `CodeGen.generateCodeSafe`
    * [x] #14823

**Comment by ray-roestenburg-da** [comment]
@S11001001 Is this issue still blocked?

**Comment by stefanobaghino-da** [comment]
If by any chance it still is, please call out the responsible team lead.
