### ISSUE TITLE
support same-named choices in TypeScript codegen

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#14091]
Design in https://github.com/digital-asset/daml/issues/13668#issuecomment-1110146425

* [x] replace `Object.assign` in template JS output with a function in `@daml/types`, similar to how `registerTemplate` supports codegen output
* [x] stop copying colliding IDs in that function
* [x] `ifaceDefTempl` needs to know choice names associated with the `TsTypeConRef`s
    * [x] pass an interface index to `genDefDataType` so this information can be included in `data TemplateDef`
    * [x] use `Omit` to remove the collisions from each of `implRefs` where relevant
* [x] ensure interface ID is sent to json-api
