### ISSUE TITLE
Can exercise roll-backed  created contracts

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#14148]
# Affected Daml version

All versions that support exception (to be confirmed)

# Bug description

- In a try block. 
  - Create a contract 
  - Throw an exception with the Contract Id of the previous contract  
 - Catch the exception and exercise the contract ID 

# To reproduce

Here a a script that allow reproducing the bug.

```
module Mod where

import DA.Exception 
import Daml.Script

template T with sig: Party 
  where 
    signatory sig

exception E with cid: ContractId T

template Op with sig: Party
  where
    signatory sig
    choice Go2: ()
      controller sig
      do 
        try do 
          cid <- create (T sig) 
          throw (E cid)
        catch (E cid) -> archive cid

test: Script ()
test = script do 
   alice <- allocateParty "alice"
   op <- submit alice $ createCmd (Op alice)
   r <- submit alice $ exerciseCmd op Go2
   pure ()
```

# Expected behavior

The exercise should fail with a `ContractNotActive` or `ContractNotFound` error 

# Additional context

* IDE 2.2.0: Exercise does not fail.
* IDE 1.18.0: Exercise does not fail.
* kv-sandbox (1.18.0, daml sandbox): Exercise does not fail.
* daml-on-sql (1.18.0, postgresql in docker): Exercise does not fail.
* canton sandbox (2.2.0, daml sandbox): Code builds, but Canton instance refuses to run due to "Illformed transaction received" error.

# TODO 

- [x] fix the test in main  #14163
- [x] add a regression test to the ledger API conformance tests  #14197
- [ ] backport the fix to 1.18.x

**Comment by remyhaemmerle-da** [comment]
cc @bame-da @stefanobaghino-da

**Comment by dylant-da** [comment]
IDE 2.2.0:  Exercise does not fail.
IDE 1.18.0: Exercise does not fail.
kv-sandbox (1.18.0, daml sandbox): Exercise does not fail.
daml-on-sql (1.18.0, postgresql in docker): Exercise does not fail.
canton sandbox (2.2.0, daml sandbox): Code builds, but Canton instance refuses to run due to "Illformed transaction received" error.
