### ISSUE TITLE
by-key operations fail after rollback archive

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#14171]
# Affected Daml version

All version supporting exception until 2.2.x

# Bug description

# To reproduce

The following script fails, while it should succeeds.

```
module Mod where

import DA.Exception 
import Daml.Script

template K 
  with
    sig: Party
  where
    signatory sig
    key sig: Party
    maintainer key

template Helper
  with sig: Party
  where
    signatory sig

    nonconsuming choice Go: ()
      with cid: ContractId K
      controller sig
      do
        try do
          exercise cid Archive
          create (K sig)
          throw (GeneralError "")
        catch (GeneralError _) -> pure ()
        fetchByKey @K sig
        pure ()


test : Script ()
test = script do
  alice <- allocateParty "alice"
  cid <- submit alice $ createCmd (K alice)
  helper <- submit alice $ createCmd (Helper alice)
  submit alice $ exerciseCmd helper (Go cid)
  pure ()
```

# Expected behavior

# Additional context

* IDE 2.2.0: Fetch fails with key not found, due to archive.
* IDE 1.18.0: Fetch fails with key not found, due to archive.
* kv-sandbox (1.18.0, daml sandbox): Fetch fails with key not found, due to archive.
* daml-on-sql (1.18.0, postgresql in docker): Fetch fails with key not found, due to archive.
* canton sandbox (2.2.0, daml sandbox): Fetch fails with key not found, due to archive.

# TODO 

- [x] check visibility for all by-key operation. #14175 
- [x] switch engine key resolution to strict mode.  #14176
- [x] drop non strict unique mode.  #14194
- [x] add test for visibility of divulged contracts.  #14206
- [ ] add regression test to ledger API conformance tests. #14212

**Comment by dylant-da** [comment]
IDE 2.2.0:  Fetch fails with key not found, due to archive.
IDE 1.18.0: Fetch fails with key not found, due to archive.
kv-sandbox (1.18.0, daml sandbox): Fetch fails with key not found, due to archive.
daml-on-sql (1.18.0, postgresql in docker): Fetch fails with key not found, due to archive.
canton sandbox (2.2.0, daml sandbox): Fetch fails with key not found, due to archive.

**Comment by cocreature** [comment]
@remyhaemmerle-da did the fix not work or why did you reopen that?

**Comment by remyhaemmerle-da** [comment]
I still have to add a regression test.
