### ISSUE TITLE
Engine/speedy-level tests for explicit disclosure

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#14227]
Engine level or speedy level tests for
- [x] Test that explicit disclosure works for contract & keys (#14436)
- [x] Test that invalidly typed contracts are rejected (#14563)
- [x] Test that non-normalized contracts are accepted (#14544)
- [x] Test that invalid key hashes are rejected (#14609)
    - ref: #13897
    - ref: #14999
- [x] Test that duplicate contract ids & keys are rejected (#14546)
- [x] Test expected behaviour when superfluous (i.e. unused) contracts are disclosed in commands (#14617)
    - ref: #14350
- [x] Test that disclosed contracts respect template/contract preconditions (i.e. ensure clauses)
    - ref: #15057
