### ISSUE TITLE
support interface subscriptions in JSON API

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#14727]
Part of #14067. Design in https://github.com/digital-asset/daml/issues/14067#issuecomment-1149150541.

* [x] #14577 
* [ ] new `ContractTypeId` resolution semantics
    - [ ] `Resolved` aliases should statically include `Definite`
    - [ ] PackageService resolvers should statically include `Definite`
    - [ ] `Template` or `Interface` should only match that kind of ctid
    - [ ] `Unknown` may match either one
* [ ] permit multiple DB rows per contract ID
    - [ ] include template IDs in `InsertDeleteStep`
* [ ] `/v1/fetch` by contract ID
* [ ] in query, resolve contract type ID sets (`CTIDS` in design) statically to either a non-empty set of template IDs or a single interface ID
* [ ] `/v1/query`
* [ ] `/v1/stream/query`
