### ISSUE TITLE
propagate template/interface ID distinction throughout JSON API

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#14814]
Exploit #14577 to ensure that every part of JSON API knows whether it is dealing with a template or interface ID. In some cases this will be _statically_, in others _dynamically_. Overall design in https://github.com/digital-asset/daml/issues/14067#issuecomment-1149150541

* [x] new `ContractTypeId` resolution semantics
    - [x] `Resolved` aliases should statically include `Definite`
    - [x] PackageService resolvers should statically include `Definite`
