### ISSUE TITLE
query store support for interface query/fetch

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#14819]
Overall design in https://github.com/digital-asset/daml/issues/14067#issuecomment-1149150541.

* [x] permit multiple DB rows per contract ID
* [x] the final caller of `ActiveContract.fromLedgerApi`, this time in `ContractsFetch`, must do as with #14815
* [x] include contract type IDs in `InsertDeleteStep`
* [x] add contract type ID argument to `Queries#deleteContracts`, in the form of `SurrogateTpId`
* [x] in `ContractsFetch#insertAndDelete`, find the appropriate SurrogateTpIds for the `deleteContracts` call
* [x] in `SearchDB#findByContractId`, remove the `ByInterfaceId` special case
* [x] in `SearchDB#search`, remove the `ByInterfaceId` special case
* [x] in `WebSocketService#fetchAndPreFilterACS`, remove the `ByInterfaceId` special case
* [x] #15316
    * [x] create two contracts with a signatory and a _different_ observer, of a template that implements an interface with a non-empty view
    * [x] using an auth **with both parties**:
    * [x] query the template ID; ensure there are 2 contracts
    * [x] query the interface ID; ensure there are 2 contracts
    * [x] query the template ID _again_; ensure there are 2 contracts
    * [x] if this fails (with too many contracts) it is most likely to be Oracle-specific; if so, and it's fine on Postgres, the `JOIN` in `OracleQueries#selectContractsMultiTemplate` is the place to start looking e894eed23ec16c236ec3a5cd65870cfafcef370d 
* [x] other test coverage is there already, as we duplicate query/WS tests with query store on and off

The issues below are "soft prerequisites"; while we can make some advances, particularly the first four above items, we might run into weird bugs without having fixes for these in place:

* [x] #15040
* [x] #15098
* [x] #14844
