### ISSUE TITLE
`/v1/query` with interface ID, without query store

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#14815]
Overall design in https://github.com/digital-asset/daml/issues/14067#issuecomment-1149150541.

* [x] depends on #14814
* [x] when `LedgerReader.damlLfTypeLookup` receives an `id` that is an interface ID, it must return a `DefDataType.FWT` that represents the interface view.  It can use the `PackageSignature#resolveInterfaceViewType` utility as the basis of this
* [x] in query, resolve contract type ID sets (`CTIDS` in design) statically to either a non-empty set of template IDs or a single interface ID
Split off #14871
* [x] in the interface case in DB query, redirect to the in-memory implementation. Leave a TODO #14819 comment here
* [x] `AcsTxStreams.transactionFilter` must use the second argument to `InclusiveFilters` for interface IDs
* [x] `domain.ActiveContract.fromLedgerApi` produces the wrong value; it should assign `templateId` to be the interface ID, and `payload` to be the associated view, as described in the design doc for its caller in `ContractsService`. This is another use of the static resolution described in step 2
* [x] test that you can query one interface ID and it returns the view, not the template payload
