### ISSUE TITLE
`/v1/stream/query` with interface ID, without query store

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#14817]
Overall design in https://github.com/digital-asset/daml/issues/14067#issuecomment-1149150541.

* [x] depends on #14814
* [x] depends on #14815
* [x] a similar query resolution to that described for #14815
  * Spin off https://github.com/digital-asset/daml/issues/14931
* [x] the transactionFilter change in #14815 should work just as well for this feature
* [x] `fetchAndPreFilterAcs` should treat the case where its predicate is an interface query, as if `daoAndFetch` is `None`. Leave a TODO #14819 comment here
* [x] another caller of `domain.ActiveContract.fromLedgerApi` must be made sensitive to this resolution, this time in `WebSocketService`
* [x] test that a single interface ID is accepted even if used for two queries
    * [x] create 4 contracts
    * [x] view should be JSON-incompatible with the template, use unique field names 
    * [x] submit a list of 2 queries on the same interface ID, such that 1 contract fails both, 1 contract passes both, 1 contract passes only the first, and 1 contract passes the second
    * [x] read in all the output, no need for fancy lazy submission
    * [x] check that you got the 3 ~queries~ contracts that passed, with matchedQueries [0, 1], [0], and [1] respectively
* [x] test that multiple distinct interface IDs, or interface ID + template ID, multiqueries are rejected 400

**Comment by chunlokling-da** [comment]
view should be JSON-incompatible with the template, use unique field names

@S11001001 Do you mean by having a interface view name different from the template?

**Comment by S11001001** [comment]
> Do you mean by having a interface view name different from the template?

No; type names do not appear in JSON encodings. Different field names within the view, compared to the template, work.
