### ISSUE TITLE
Java typed-decoders features

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#15014]
There is now a collection of associated [`ledger client facade` issues](https://github.com/digital-asset/daml/issues?q=is%3Aopen+is%3Aissue+label%3A%22ledger+clients+facade%22+label%3Acomponent%2Fjava-ecosystem+), all somewhat loosely dependent on #14313 (though truly only `interface FromValue` is required for all of them).

* [ ] on the querying side, ACS and transaction streams: #14969 needs very little of decoders for templates, since `TemplateCompanion` already carries decoders. It's a little trickier, but interface views can also be incorporated by adding interface views to `InterfaceCompanion`
* [ ] on the choice metaprogramming side, there is #14329. The basics can be done without decoders, but full support for decoding choice arguments and return types needs them
    * [ ] this would also close #14421 
* [ ] `ChoiceMetadata` may also be a good basis for #14312. However, we have to seriously discuss what we want to break with that change
* [ ] #13768 _does not need anything from value decoders_.
    * [ ] However, we can use this for the very similar #12897. We don't need to generate any code for #12897, since it can be derived from the values introduced in #13768 if we also have #14329

**Comment by S11001001** [comment]
While there is ever-increasing overlap between the untyped-value classes like `CreatedEvent` and their typed-value counterparts like `Created` and `Contract<...>`, we won't unify them as part of this metaissue.

Additionally, as of this writing our only plans regarding this metaissue are to finish the exercise event ideas included above, and beyond that allow changes to `quickstart-java` and downstream help to discover new features, at least until we have another idea.
