### ISSUE TITLE
interface view decoders

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#15125]
Build upon #14313, and support #14969, by having `InterfaceCompanion` also supply a `ValueDecoder<View>`.

* [x] #15017
* [x] `InterfaceCompanion`'s tparams should be `<I, View>`
* [x] `ContractTypeCompanion`'s tparams should be `<Marker, Data>`. `ContractCompanion` should pass `Data` for *both*. They should be `I, View` for `InterfaceCompanion`
* [x] change the `INTERFACE` class we generate to pass the view type as the second tparam, and pass a `ValueDecoder<View>` as a param to `super`

**Comment by chunlokling-da** [comment]
I am thinking about whether to put the `public final ValueDecoder<Data> valueDecoder` in `InterfaceCompanion` or `ContractTypeCompanion`. I believe we ultimately would like to put it in ContractTypeCompanion as the both template and interface should provide a ValueDecoder<>. I tried to put it in ContractTypeCompanion but I have encounter some required changes in generate Template class. @S11001001  Do you think it is good enough for this issue to put the valueDecoder in InterfaceCompanion but not in ContractTypeCompanion yet?

**Comment by S11001001** [comment]
> Do you think it is good enough for this issue to put the valueDecoder in InterfaceCompanion but not in ContractTypeCompanion yet?

@chunlokling-da It can be put in all three. Define this (package-private) method:

```java
<Z> Z fold(Function<? super ContractCompanion<?, ?, Data>, Z> template,
    Function<? super InterfaceCompanion<Marker, Data>, Z> iface)
```

and then implementing `valueDecoder` in the `ContractTypeCompanion` by calling the other two should become straightforward.

**Comment by S11001001** [comment]
@chunlokling-da On the other hand, maybe not so straightforward. Yeah, it's fine to have it in the `InterfaceCompanion` but not in `ContractTypeCompanion` for this issue. However, I think this might imply that we have a problem with decoding interface contract IDs that we should fix separately.
