### ISSUE TITLE
Tests for projection Java API covering common usage

### ISSUE THREAD

**Issue by ray-roestenburg-da** [digital-asset/daml#15500]
Add more unit tests in JavaApiSpec to cover the most common use cases of the Java API.

- [x] project created events
- [x] project created and archived events
- [x] project exercised events
- [x] project tree events
- [x] project using a batch operation
- [x] continue projection where it left off
- [x] failure cases
- [x] project using generated code

overview: https://github.com/digital-asset/daml/issues/15463
origin: https://github.com/DACH-NY/projection/issues/43
