### ISSUE TITLE
Projection: Auto-create projection table if not present

### ISSUE THREAD

**Issue by ray-roestenburg-da** [digital-asset/daml#15544]
- [ ] Take the projection table name from config (or take a prefix from config if that is simpler), `reference.conf` specifies "projection" as default. Users can override with `application.conf` (and also specify a specific user /passwd that has permissions to create / migrate the table.
- [ ] Use flyway internally to auto-create the projection table if it does not exist, on first use of a projection (probably implemented in `Init`).
- [ ] In `TestDb` make sure tests can get a unique projection table.
- [ ] Future version of the projection library can specify migrations for the projection table if needed.
