### ISSUE TITLE
Public SDK artifacts to public repos -- maven central and/or bintray jcenter

### ISSUE THREAD

**Issue by dasormeter** [digital-asset/daml#170]
To ease barrier to entry of using SDK so developers do not need to add custom repositories or manage their bintray credentials, publish SDK artifacts to a public repository that is already defined by default for most build tools (maven / sbt)

Leading contenders are maven central and bintray jcenter

Approach for publishing outlined here https://reflectoring.io/bintray-jcenter-maven-central/

For general SDK userbase we want to optimise to making the software available in readily accessible public locations (maven central, jcenter bintray) and that is the reason we want to get our software to those public repos.

Additionally we need to consider that many enterprise institutions will not have public internet acces enabled to pull from public repos by default and having all the artifacts in the single bintray private repo location would be adventagous.

So recommendation is we continue to our our private bintray as a staging repo and promote to public repos from there.

We can follow a publish to maven central / jcenter bintray approach as outlined in this article https://reflectoring.io/bintray-jcenter-maven-central/

### Things to consider

1.  There are no credentials or special license agreements required for JAR artifacts that are published through the public repositories.  Therefore, if users pull these in via Group-Artifact-Version (GAV) definition in their build files, they will immediately have the classes and artifacts ready to use.

### References
https://reflectoring.io/bintray-jcenter-maven-central/
https://maven.apache.org/repository/guide-central-repository-upload.html

**Comment by nicholassmith-da** [comment]
Guide to publishing artefacts to Maven Central at:
https://maven.apache.org/repository/guide-central-repository-upload.html

**Comment by nicholassmith-da** [comment]
**Task Breakdown**
- [ ] Update pom.xml template used by the Bazel rules to conform to the Maven Central guidelines.
  - [ ] Confirm license is Apache 2.0?
  - [ ] What name and description do we use (derive from Bazel info)
  - [ ]  SCM tag - hardcode the GitHub project.
  - [ ]  Developer info. What email to use?
- [ ] Add Bazel rules to build sources and javadoc for all artefacts to be published
- [ ] Add PGP Signing for release artefacts (need to involve @garyverhaegen-da)
- [ ] Request access to Sonatype Repo which is mirrored by Maven Central
- [ ] Remove the `repositories` and `pluginRepositories` block from the examples
- [ ] Update documentation
- [ ] Legal Signoff
- [ ] Change Bazel to publish to Sonotype Repo

**Comment by nicholassmith-da** [comment]
Example on how to upload to a Sonatype repo:
```curl -v -u admin:admin123 -X POST 'http://localhost:8081/service/rest/v1/components?repository=maven-releases' -F maven2.groupId=com.google.guava -F maven2.artifactId=guava -F maven2.version=24.0-jre -F maven2.asset1=@guava-24.0-jre.jar -F maven2.asset1.extension=jar -F maven2.asset2=@guava-24.0-jre-sources.jar -F maven2.asset2.classifier=sources -F maven2.asset2.extension=jar```

**Comment by nicholassmith-da** [comment]
Also being tracked by the DA Security Team as:
https://digitalasset.atlassian.net/browse/HELP-2270

**Comment by nicholassmith-da** [comment]
Edwards requests to Sonatype for accounts:

https://issues.sonatype.org/browse/OSSRH-48690
https://issues.sonatype.org/browse/OSSRH-48691

**Comment by nicholassmith-da** [comment]
Some information of the Sonatype Nexus workflow:
https://github.com/sonatype/nexus-maven-plugins/blob/master/staging/maven-plugin/WORKFLOWS.md

**Comment by cocreature** [comment]
fixed
