### ISSUE TITLE
[engine] Smart Contract Upgrading Implementation (Milestone 1)

### ISSUE THREAD

**Issue by nickchapman-da** [digital-asset/daml#17082]
Engine work to support Upgradng Milestone 1:

- Latest [requirements document](https://docs.google.com/document/d/10q3LYdW4FbtORhPtzOpJDoHSe64LEyNrulqdLFF4AFc/edit?pli=1)
- Continuing work started in [MVP](https://github.com/digital-asset/daml/issues/16151)

**Comment by nickchapman-da** [comment]
Steps (not necessarily in this order)

- [ ] Update existing `softFetch`/`softExercise` integration tests to match latest required behaviour. i.e. it must work for any types which satisfy the _compatibility_ relation. And specifically, work for downgrades. Fix existing implementation.

- [ ] Implement the _compatibility_ relation (i.e code to drop/make-None) within `importValue`/`translateValue`, replacing the current code in `SBPromoteAnyContract` (which is not quite in the right place)

- [ ] Add engine level unit tests for upgrading and downgrading.

- [ ] Refuse to downgrade optional field values which are not `None` (test and imp)

- [ ] Control upgrading behaviour via engine-startup feature flag (will need to be passed from Canton)

- [ ] Ensure changes support Ratko's canton level integration test [PR](https://github.com/DACH-NY/canton/pull/13310). Specifically, so we can replace the related _hack_ [PR](https://github.com/digital-asset/daml/pull/17063) in the daml repo.

**Comment by nickchapman-da** [comment]
### interaction with contract-caching

Following the work to move the _compatibility transformation_ into `importValue` it became clear there is a interaction with contract caching (in the engine) which needs to be resolved.

Contract caching prevents the engine from asking the ledger for the same contract twice. Currently the (LF) Value for the contract (received from the ledger) is first converted to an `SValue` by `importValue` before being cached.

`importValue` requires a type to do it's work. Previously (before #17095) it used the type associated with the contract data. Now, to support upgrades, we use the type coming from the code (fetch/exercise) we are running, and then up/down-grade as necessary. Potentially, it seems that the same contract value could be used (fetch/exercise) at two different types (type versions).

This does not play well with the caching of the `SValue` resulting from `importValue`

Remy and I discussed two potential solutions, presented here:
https://github.com/digital-asset/daml/pull/17095#issuecomment-1630382251
```
A: cache an (LF) Value. Then convert to SValue on each import
B: cache SValue (like now). Then convert to a new SValue on each import.
```

We believe that B has too much subtlety and complexity, and scope for bugs.
We agreed that we should attempt A in the first instance.

**Comment by dylant-da** [comment]
Looks done - only unmarked item is "Allow upgrading of disclosed contracts", closing as done
