### ISSUE TITLE
Add reader of LF1 type signature

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#18821]
Todo:

- [x] Make Dar reader able to ingest different proto #18940
- [x] Copy lf1 proto to main, ~remove expressions from proto~ #18940
- [x] Copy the lf1 decoder to main, remove everything that decodes expressions #18940
- [x] Adapt the archive reader to handle 2 decoders #18940
- [x] Add back retroactive instances to the AST (minor change: a list or pairs of template/implements) #18876
- [x] Define a dummy metadata for packages that don’t have one. (Should only concern stable packages.) #18940
- [ ] Add a method to the archive reader to read the type signature directly.
