### ISSUE TITLE
Tracking issue for Windows-specific hacks

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#582]
Let’s use this issue to keep track of all the hacks that we have added to make Windows work and check off the ones that we’ve removed:

- [x] Inline C2hs generated files
- [x] Remove use of version macros since they are not set for `hsc2hs`.
- [ ] Linker hacks of various forms (TODO add more detail)
  - [ ] Patch `rules_haskell` to add `extra-libraries` to `grpc-haskell-core` package configuration file.
  - [ ] Hard-code Windows specific linking (`ws2_32`) in `fat_cc_library`.
- [ ] Patch GHC bindist to remove `libstdc++.dll.a` and `libwinpthread.dll.a`.
- [x] Workaround for non-hermetic `./configure` step in `network`. See `3rdparty/haskell/BUILD.network` for a description.

**Comment by stefanobaghino-da** [comment]
@cocreature If there are open points it's probably better to create new, separate tickets for them. If by any chance these have been solved in the meantime than congrats, you can close this issue. :tada:

**Comment by stefanobaghino-da** [comment]
(well, if you open new issues you can close this one anyhow, so :tada: )

**Comment by cocreature** [comment]
closing
