### ISSUE TITLE
Tracking issue for an initial Windows SDK release

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#602]
Now that we have an SDK release tarball, let’s use this issue to track what we have already tried on Windows and what problems we ran into that should be addressed before we do an initial release:
- [x] Extracting the tarball and installing using `.\daml\daml.exe install . --activate`
  Seems to work fine!
- [x] “Symlink” in `bin/daml` that points to `sdk/SDK_VERSION/daml/daml`.
   Fixed in #624 
- [x] Create a new project with `.\daml\daml.exe new <path-to-project>`
  Seems to work fine
- [x] `.\daml\daml.exe package` in the newly created project.
  Works fine and produces `quickstart.dar`.
- [x] `.\damlc\da-hs-damlc-app.exe test Main.daml` where `Main.daml` contains
```
daml 1.2
module Main where
test = scenario do
  assert False
```

Fixed in #629 

- [x] Sandbox: Start with `C:\Users\admin\AppData\Roaming\daml\sdk\0.12.7\daml\daml.exe sandbox -- --port 6865 -- --scenario Main:setup quickstart.dar`
  Seems to work!
- [x] Navigator: Start with `C:\Users\admin\AppData\Roaming\daml\sdk\0.12.7\daml\daml.exe navigator server` (requires sandbox to be running), check Contracts, Templates and Owned Ious tab as described in the test plan https://docs.google.com/document/d/16amcy7bQodXSHjEmKhAUiaPf6O92gUbch1OyixDEvSM/edit?ts=5c40550b#heading=h.qp6m2qmrzdm
  Seems to work!
- [x] Navigator and Sandbox should be killable with Ctrl-C
Currently they seem to ignore that. Might be fixable with `delegate_ctlc` and/or `use_process_jobs`.
I think this is fixed.

- [x] `code --extensions-dir C:\Users\admin\AppData\Roaming\sdk\0.12.7` after adding `C:\Users\admin\AppData\Roaming\sdk\0.12.7\daml` to PATH

Extension is loaded successfully, scenario results seem to work, errors (both scenario errors and compile errors) show up in the problems list but I get no red squiggly lines. The reason for that is that we don’t properly convert filepaths to URIs on Windows.

Fixed in #737 
- [x] `daml build`
  Fails when calling `ghc-pkg` which does not find the global package db. I think this might also be an issue on Linux on systems that don’t have dev-env setup. Fixed in #666 
- [x] `daml start`
  Fixed in #694 
- [x] `daml studio`
  Fixed in #693 
- [x] Release SDK tarball on Windows
  Fixed in #677 
- [x] Upgrade to newer versions of VSCode extension in`daml studio`.
  Fixed in #703 
- [x] Check that `daml install latest` works

**Comment by cocreature** [comment]
We have a first beta version now, so let’s close this and use separate issues for new things that pop up.
