### ISSUE TITLE
Review and extend JSON API JWT documentation

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#6951]
There are a few topics that we need to reflect in the docs (the same questions have been asked on discuss.daml.com and slack multiple times).

That is the doc that needs to get extended/reviewed: https://docs.daml.com/json-api/index.html#choosing-a-party

### TODO:
- [ ] document JSON API and Sandbox JWT relation (the first is a subset of the second)
- [ ] document which fields are required for JSON API and which endpoints infer Ledger ID, Application ID and Party from JWT
  + All endpoints except pass-through (command submission)
  + What about /v1/query ???
  + What about /v1/stream/query ???
- [ ] document pass-through endpoints, explain that pass-through endpoints don't need anything from JWT
  + /v1/parties
  + /v1/parties/allocate (needs admin JWT)
  + /v1/packages
- [ ] document that JSON API does not do any authentication/authorization and passes the JWT as is to the Ledger

**Comment by cocreature** [comment]
Part of this has been addressed by #7133 so this could be a s simple as going through the docs and making sure that all points are covered.

**Comment by cocreature** [comment]
Looked into it and it seems fine with the new changes.
