### ISSUE TITLE
Issues in the DAML Trigger API

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#7392]
This is a tracking issue for things that are currently awkward/complicated in the trigger API and potentially require breaking changes and therefore need to be addressed before moving triggers out of early access:

- [x] Time is passed as a separate parameter instead of relying on `getTime` which is what users know from `Update` and `Script`. (fixed in #7456)
- The number of arguments to the rule is quite large and a lot of them are unused. I don’t think removing all of them is necessarily a good idea, but some can probably go:
  - [x] Users have to pass around the ACS instead of `getContracts` being monadic. You can argue what is better but it is monadic in Script (and has to be) and the number of parameters on the rule is a real source of confusion. (#7632)
  - [x] The list of commands in flight is passed to the rule. If we hide it behind a monadic API for accessing it, we can further clear up the list of arguments. (#7600)
  - [x] (not doing this for now) Party of the trigger, We do need to expose this somehow and I think this is one of the cases where it’s probably easier to put it in as an argument rather than exposing it via a monadic API.
  - [x] User-defined state. Not quite sure about this one, I think it is so common to not use it, that hiding it behind a monadic API might be better but I don’t feel strongly about this. (#7674)
- [x] `getContracts` is not called `query`. You can argue what is the better name here but I think consistency with script would be very helpful for users.
- [x] (not doing this for now) `emitCommands` and `submitCommands` may also be made more consistent or clear, as mentioned in https://github.com/digital-asset/daml/pull/7456#discussion_r498648300
- [x] The user-defined state is exposed inconsistently. Currently, you get access to it everywhere but you cannot modify it from the rule. (#7674)
- [ ] The commands in flight are only exposed in the rule. Exposing them in `updateState` might be useful. (#7787)

I think for the changes that move from a parameter to providing a monadic API, we should at least have one release where users can migrate and things are available in both ways before we kill the parameters.

**Comment by S11001001** [comment]
>     * The user-defined state is exposed inconsistently. Currently, you get access to it everywhere but you cannot modify it from the rule.

Honestly I thought this was intentional, considering that this restriction isn't inherited from low-level `update`.

**Comment by cocreature** [comment]
> Honestly I thought this was intentional, considering that this restriction isn't inherited from low-level `update`.

It was but I’m not sure it makes sense. Tracking the commands that you submitted or some information about them in the user-defined state seems sensible and that doesn’t work with the current API.

**Comment by S11001001** [comment]
Some of these changes seem to direct towards introducing a monad for `updateState` (as `TriggerA` is to `rule`) and putting their common actions in an mtl-style class like `HasTime`. If making the language you use in `updateState` and `rule` more common is desirable, we might as well introduce this sooner rather than later.

**Comment by cocreature** [comment]
I’ve checked off the party item and the `submitCommands` thing since I think it doesn’t make sense to focus on this atm. That leaves us with only exposing the commands in flight in a state update which seems easy enough to do.
