### ISSUE TITLE
Require authorization on trigger service endpoints (if enabled)

### ISSUE THREAD

**Issue by aherrmann-da** [digital-asset/daml#7723]
- [x] `/v1/start` requires `actAs:PARTY` https://github.com/digital-asset/daml/pull/7654
- [x] `/v1/stop/UUID` requires `actAs:PARTY` #7750
- [x] `/v1/status/UUID`  requires `readAs:PARTY` #7761
- [x] `/v1/list` requires `readAs:PARTY` #7761
- [x] `/v1/upload_dar` requires `admin` (or similar, see https://github.com/digital-asset/daml/pull/7654#discussion_r504094746) #8193

Part of #6923.
