### ISSUE TITLE
Exceptions in DAML

### ISSUE THREAD

**Issue by sofiafaro-da** [digital-asset/daml#8020]
Over-arching ticket for implementing exceptions in DAML (_"one ring to rule them all"_), so we have an issue number to keep track of work to be done. See also [the exception milestone](https://github.com/digital-asset/daml/milestone/54).

TODO:

- [x] update LF specification
  - [x] syntax & semantics of exception handling (implemented in #8068 #8111)
  - [x] update existing primitives & constructs to throw more appropriate exceptions
- [x] update LF protobuf (implemented in #8087)
- [x] change DAML-LF AST
  - [x] on Haskell side (implemented in #8112)
  - [x] on Scala side
- [x] update type checker
  - [x] on Haskell side (#8112, #8137)
  - [x] on Scala side
- [x] update serializability checker
  - [x] on Haskell side (#8112, #8151)
  - [x] on Scala side
- [x] update LF engine
  - [x] implement exception builtins
  - [x] implement exception handling
  - [x] update existing primitives to throw appropriate exceptions
- [x] update standard library
  - [x] add `DAML_EXCEPTIONS` feature (#8114)
  - [x] add `DA.Exception` module (#8023)
  - [x] run through existing standard library functions and see if they should throw more appropriate exceptions (#9783)
- [x] update surface syntax
  - [x] prepare examples of surface syntax & its desugaring
  - [x] implement syntax for declaring exception types
  - [x] implement try-catch block syntax
  - [x] update daml studio language file to highlight exception keywords
  - [x] (not implemented, left as separate issue) implement more powerful ensure statement (issue #3571 but read exception design doc)
- [x] update data-dependencies
  - [x] recognize built-in exception types
  - [x] re-export exceptions
  - [x] add a test that involves raising and catching built-in exceptions across data-dependency boundaries (#9799)
- [x] release a new LF version
  - [x] update the LF version for the `DAML_EXCEPTIONS` feature in `DA.Daml.Lf.Ast.Version`
  - [x] update the LF version for `DA.Internal.Exception` in the "generate stable package" rule
  - [x] update stable package test (`compiler/damlc/tests/src/stable-packages.sh`) and other references to exception stable packages.
- [x] update ledger-api-test-tool with tests that involve catching and throwing exceptions

**Comment by cocreature** [comment]
Conclusion from today’s meeting:

We cannot catch exceptions from old LF versions. A participant might need to validate nodes from that older LF version while it doesn’t understand the new LF version. There are two versions that are possible here:
1. We tie the version of an exception statically to the code throwing it.
2. We tie the version of an exception dynamically to the version of the choice that caused it.

We decided on 1 since it’s simpler to implement and seems more predictable at the LF level. There is a slight issue with cross-LF inlining in damlc. This doesn’t cause technical issues but it could be a bit surprising. Given that we don’t inline particularly aggressively, the plan for now is to not worry about this.

**Comment by cocreature** [comment]
Oh and the other topic we discussed is changes to the ledger API. In the first iteration, we won’t expose catch nodes in the transaction tree service and will instead handle that together with addition of fetch nodes. We might want to expose exceptions that propagate up to the top-level so we can nicely rethrow them in Daml Script but even that is a separate issue and not required for a first verison.

**Comment by cocreature** [comment]
:partying_face:
