### ISSUE TITLE
Non-repudiation middleware prototype

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#8598]
"Non-repudiation refers to a situation where a statement's author cannot successfully dispute its authorship or the validity of an associated contract." ([Wikipedia article](https://en.wikipedia.org/wiki/Non-repudiation))

Specifically in the context of Daml ledgers, the non-repudiation middleware acts as a (reverse) proxy that:
* has access to a trusted source of public keys used and recognized by participant users
* accepts and forwards commands to an upstream participant exclusively if they are signed with a know key
* maintains a repository of signed commands for further inspection

A prototype of such middleware is currently available on [this](https://github.com/digital-asset/daml/commit/6ea70c4b45d55cbf62caa3cc03dd70310ca79b87) commit.

The diff is too big and too broad in scope for review due to some changes that have been made to make testing the middleware more practical, so it will be broken up in the following PRs.

- [x] Add a library that defines `Resource` factory methods for gRPC servers and channels (#8604)
- [x] Enhance `grpc-test-utils` and `grpc-reverse-proxy` to use `Resource`s (#8606)
- [x] Enable `ledger-api-test-tool` to be used as a library (#8607)
- [x] Add the first non-repudiation middleware prototype, passing all conformance tests (#8608)

This issue can be considered closed when these PRs are all merged.

Note that the commit linked above also includes client-side changes to the bindings that can be probably delayed to a further phase, following more design work. None of the work in that commit actually needs bindings to be updated as all testing has been done using bare gRPC libraries.

Further work to ensure that the non-repudiation middleware is viable for early access will be tracked as part of [this milestone](https://github.com/digital-asset/daml/milestone/55).
