### ISSUE TITLE
LF 1.14

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#9914]
Previous LF version ticket: #8591

this version of LF should include:

- [x] exceptions #8020
- [x] byKey flag Node #9632
- [x] preview version (in SDK 1.14) #9906
- [X] release version (in SDK 1.15) #10077
- [x] bump ledger API version #10175
- [ ] default compiler output (in SDK 1.16) #10394
